---
kind: pipeline
name: generate-schema

steps:
- name: setupphp81
  image: docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
    - docker build --rm -t snowcookie/generate-schema-php81 ./docker/php81

- name: testphp81
  image: snowcookie/generate-schema-php81:latest
  pull: if-not-exists
  volumes:
  - name: vendorphp81
    path: /drone/src/vendor
  commands:
    - composer install
    - vendor/bin/phpunit --testsuite "Package Test Suite" -v --debug
  depends_on:
    - setupphp81

services:
- name: snowcookie-generate-schema-mysql
  image: mysql:8
  pull: always
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
  command: [ "--default-authentication-plugin=mysql_native_password" ]

- name: snowcookie-generate-schema-postgres
  image: postgres:15
  pull: always
  environment:
    POSTGRES_DB: homestead
    POSTGRES_PASSWORD: secret
    POSTGRES_USER: homestead

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

- name: vendorphp81
  host:
    path: /home/snowcookie/drone/${DRONE_REPO_NAME}/php81/vendor
