kind: pipeline
name: generate-schema

steps:
- name: setup
  image: docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
    - docker build --rm -t snowcookie/generate-schema-php71 ./docker/php71

- name: test
  image: snowcookie/generate-schema-php71
  working_dir: /application
  volumes:
  - name: vendor
    path: ./vendor
  commands:
    - composer install
    - vendor/bin/phpunit --testsuite "Package Test Suite" --debug

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

- name: vendor
  host:
    path: /home/snow/drone/${DRONE_REPO_NAME}/vendor