kind: pipeline
name: generate-schema

steps:
- name: setup
  image: docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
    - docker build --rm -t snowcookie/generate-schema-php73 ./docker/php73

- name: test-without-database
  image: snowcookie/generate-schema-php73:latest
  pull: if-not-exists
  volumes:
  - name: vendor
    path: /drone/src/vendor
  commands:
    - composer install
    - vendor/bin/phpunit --testsuite "Package Test Without Database Suite" -v --debug

- name: test-all
  image: snowcookie/generate-schema-php73:latest
  pull: if-not-exists
  volumes:
  - name: vendor
    path: /drone/src/vendor
  commands:
    - sleep 20s
    - vendor/bin/phpunit --testsuite "Package Test Suite" -v --debug

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

- name: vendor
  host:
    path: /home/snow/drone/${DRONE_REPO_NAME}/vendor

services:
- name: snowcookie-generate-schema-mysql
  image: mysql:8.0
  ports:
    - 3306
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret

- name: snowcookie-generate-schema-postgres
  image: postgres:11.3
  ports:
    - 5432
  environment:
    POSTGRES_DB: homestead
    POSTGRES_PASSWORD: secret
    POSTGRES_USER: homestead