kind: pipeline
name: generate-schema

steps:
- name: setup
  image: docker
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
    - docker build --rm -t snowcookie/generate-schema-php71 ./docker/php71

- name: test-without-database
  image: snowcookie/generate-schema-php71:latest
  pull: if-not-exists
  volumes:
  - name: vendor
    path: /drone/src/vendor
  commands:
    - composer install
    - vendor/bin/phpunit --testsuite "Package Test Suite" --debug

- name: test-all
  image: snowcookie/generate-schema-php71:latest
  pull: if-not-exists
  volumes:
  - name: vendor
    path: /drone/src/vendor
  commands:
    - sleep 20s
    - vendor/bin/phpunit --testsuite "Package Test All Suite" --debug

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

- name: vendor
  host:
    path: /home/snow/drone/${DRONE_REPO_NAME}/vendor

services:
- name: snowcookie-generate-schema-mysql
  image: mysql:8.0
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret