version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: snowcookie-generate-schema-mysql
      working_dir: /application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret

    php73:
      build:
        context: .
        dockerfile: docker/php73/Dockerfile
      container_name: snowcookie-generate-schema-php73
      working_dir: /application
      volumes:
        - ./:/application
      depends_on:
        - mysql
      links:
        - mysql
