version: "3.1"
services:

  mysql:
    image: mysql:8
    container_name: snowcookie-generate-schema-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
    command: --default-authentication-plugin=mysql_native_password

  postgres:
    image: postgres:15
    container_name: snowcookie-generate-schema-postgres
    environment:
      - POSTGRES_DB=homestead
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=homestead

  php81:
    build:
      context: .
      dockerfile: docker/php81/Dockerfile
    container_name: snowcookie-generate-schema-php81
    working_dir: /application
    volumes:
      - ./:/application
    depends_on:
      - mysql
      - postgres
    links:
      - mysql
      - postgres
