version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: snowcookie-generate-schema-mysql
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
      command: --default-authentication-plugin=mysql_native_password

    postgres:
      image: postgres:11.3
      container_name: snowcookie-generate-schema-postgres
      environment:
        - POSTGRES_DB=homestead
        - POSTGRES_PASSWORD=secret
        - POSTGRES_USER=homestead

    php73:
      build:
        context: .
        dockerfile: docker/php73/Dockerfile
      container_name: snowcookie-generate-schema-php73
      working_dir: /application
      volumes:
        - ./:/application
      depends_on:
        - mysql
        - postgres
      links:
        - mysql
        - postgres
